name: Delete Merged Pull Requests

on:
  pull_request:
    types: [closed]

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            
